FROM golang:1.25-alpine AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o shipment-service ./cmd/shipment-service

FROM alpine:latest
WORKDIR /app
COPY --from=build /app/shipment-service .
CMD ["./shipment-service"]
